# Generated by Django 4.1.4 on 2022-12-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropStaff',
            fields=[
                ('role', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='stockCategory',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='stockSubCategory',
            fields=[
                ('sub_category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stockcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alias_name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stockcategory')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stocksubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='staffManagement',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.dropstaff')),
            ],
        ),
    ]
